-- Run after initial schema. Safe to run multiple times (IF NOT EXISTS).

ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS image TEXT DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS area_type VARCHAR(30) NOT NULL DEFAULT 'city';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS state VARCHAR(80) DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS district VARCHAR(80) DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS city VARCHAR(80) DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS village VARCHAR(120) DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS business_hours VARCHAR(80) DEFAULT '';

ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier_id INTEGER REFERENCES suppliers(id) ON DELETE SET NULL;
